sudo: required

services:
      - docker

before_install:
      - docker pull qserv/stack:centos_latest
      - docker pull qserv/stack:debian_latest

script:
      - docker build -t qserv/mariadb:centos docker/centos
      - docker build -t qserv/mariadb:debian docker/debian
