sudo: required

services:
      - docker

before_install:
      - docker pull qserv/centos_stack:latest
      - docker pull qserv/debian_stack:latest

script:
      - docker build -t qserv/mariadb:centos docker/centos
      - docker build -t qserv/mariadb:debian docker/debian
